apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::592526131074:role/getting-started-eks2021111505015593560000000d"
      "username": "system:node:{{EC2PrivateDNSName}}"

    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::592526131074:role/service-role/codebuild-oai-nrf-build-service-role"
      "username": "codebuild-oai-nrf-build-service-role"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-15T05:02:03Z"
  labels:
    app.kubernetes.io/managed-by: Terraform
    terraform.io/module: terraform-aws-modules.eks.aws
  name: aws-auth
  namespace: kube-system
  resourceVersion: "58611"
  uid: e8069a08-29eb-4ed0-af08-b6d2d9e1c385
